### ISSUE TITLE
Issue with tutorial3.cpp

### ISSUE THREAD

**Issue by diegohavenstein** [loarabia/Clang-tutorial#22]
I had a little issue while trying the third tutorial. After typing make and running the executable, the output is

testInclude.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^

I did not change the files in any way. I'm running Ubuntu Linux.

Any help would be highly appreciated!
Thanks,
Diego

**Comment by loarabia** [comment]
I think I have this fixed now in all of the tutorials.
